apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
#  name: cast
spec:
  replicas: 2
  selector:
    matchLabels:
#      app: cast
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
#        app: cast
    spec:
      containers:
#        - name: cast
#          image: "dahansop/jenkinsexam-cast:V39.0"
#          imagePullPolicy: IfNotPresent
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secret
#                name: cast-secret
          ports:
            - containerPort: {{ .Values.service.port }}
#            - containerPort: 8000
          

