apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
#  name: cast-secret
type: Opaque
data:
# postgresql://admin:password@cast-db:5432/castdb
  DATABASE_URI: {{ default "" .Values.secret.databaseUri | b64enc | quote }}
#  DATABASE_URI: cG9zdGdyZXNxbDovL2FkbWluOnBhc3N3b3JkQGNhc3QtZGI6NTQzMi9jYXN0ZGI=

