apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
#  name: cast-service
  labels:
    app: {{ .Chart.Name }}
#    app: cast
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
#    - port: 8000
  selector:
    app: {{ .Chart.Name }}
#    app: cast

