apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
#  name: cast-db
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-db
#    app: cast-db
  ports:
  - port: {{ .Values.servicedb.port }}
#  - port: 5432
