apiVersion: v1
kind: ConfigMap
metadata:
   name: {{ .Chart.Name }}-db-configmap
#  name: movie-db-configmap
data:
  POSTGRES_DB: {{ .Values.configmap.dbname }}
#  POSTGRES_DB: moviedb
  POSTGRES_HOST_AUTH_METHOD: {{ .Values.configmap.hostAuthMethod }}
#  POSTGRES_HOST_AUTH_METHOD: trust
