apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
#  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
#      app: movie
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
#        app: movie
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
#        - name: movie
#          image: "dahansop/jenkinsexam-movie:V39.0"
#          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-secret
#                name: movie-secret
          ports:
            - containerPort: {{ .Values.service.port }}
#            - containerPort: 8000
          

