apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
#  name: movie-secret
type: Opaque
data:
# postgresql://admin:password@movie-db:5432/moviedb
  DATABASE_URI: {{ default "" .Values.secret.databaseUri | b64enc | quote }}
#  DATABASE_URI: cG9zdGdyZXNxbDovL2FkbWluOnBhc3N3b3JkQG1vdmllLWRiOjU0MzIvbW92aWVkYg==
# http://cast-service:8000/api/v1/casts/
  CAST_SERVICE_HOST_URL : {{ default "" .Values.secret.castServiceUrl | b64enc | quote }}
#  CAST_SERVICE_HOST_URL : aHR0cDovL2Nhc3Qtc2VydmljZTo4MDAwL2FwaS92MS9jYXN0cy8=

