apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-db
#  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
#      app: cast-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db
#        app: cast-db
    spec:
      containers:
      - name: {{ .Chart.Name }}-db
#      - name: chart-db
        image: "postgres:12.1-alpine"
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ .Chart.Name }}-db-secret
#            name: cast-db-secret
        - configMapRef:
            name: {{ .Chart.Name }}-db-configmap
#            name: cast-db-configmap
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: {{ .Chart.Name }}-db-storage
#        - name: cast-db-storage
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: {{ .Chart.Name }}-db-storage
#      - name: cast-db-storage
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-db-pvc
#          claimName: cast-db-pvc
