apiVersion: v1
kind: Secret
metadata:
#  name: cast-db-secret
  name: {{ .Chart.Name }}-db-secret
type: Opaque
data:
# password
  POSTGRES_PASSWORD: {{ default "" .Values.secretdb.password | b64enc | quote }}
#  POSTGRES_PASSWORD: cGFzc3dvcmQ=
# admin
  POSTGRES_USER: {{ default "" .Values.secretdb.username | b64enc | quote }}
#  POSTGRES_USER: YWRtaW4=

